server:
  port: 18181

mysql:
  host: localhost
  port: 3306
  password: wendadawen
  userName: root
  databaseName: wecqu

proxy:
  vpn: false
  jwc: false
  lib: false
  card: false
  graduated: false
  cas: false
  my: false
  youth: false
  proxy_server: frp.sramar.com:9999
  proxy_user: xproxy
  proxy_pwd: Xproxy_xuan

cqu:
  term_current_my: 2023秋
  term_current_mis: 1/秋
  term_name: 2023-2024学年第一学期
  term_start_date: 2023-08-28
  term_end_date: 2024-01-15